### ISSUE TITLE
建议去掉 store 层的直接操作

### ISSUE THREAD

**Issue by shichaoyuan** [polarismesh/polaris-cleanup#2]
store 层的细节应该封装在 polaris-server 中，由 polaris-server 对外暴露必要的运维接口。
在 cleanup 中直接操作具体的数据源，会造成很多不必要的负担，比如说调整数据源的细节很可能也需要 cleanup 适配，这样运维起来会挺麻烦。

**Comment by chuntaojun** [comment]
我觉得是可以，有兴趣处理下吗

**Comment by shichaoyuan** [comment]
好，分给我吧，搞一下。
